Algoritmo "AlgLogicProgAula05-Ex2"

Var

   num1, num2 : real

Inicio

   escreval("ALGORITIMO DE COMPARÇÃO DE NÚMEROS.")
   escreval("")
   escreva("Digite um número: ")
   leia(num1)
   escreval("")
   escreva("Digite mais um número: ")
   leia(num2)
   
   se num1 = num2 entao
      escreval("")
      escreval("Os números são iguais.")
         senao
            escreval("")
            escreval("Os números são diferentes.")
   fimse
   
Fimalgoritmo